"use client";

import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
} from "recharts";

export type AgentTrendPoint = {
  imported_at: string;
  data_period: string | null;

  creators: number;
  diamonds: number;
  matches: number;

  meetingDays: number;
  meetingHours: number;

  complete: number;
  needsAttention: number;

  completionRate: number;
};

type Props = {
  agent: string;
  history: AgentTrendPoint[];
};

function formatDate(value: string) {
  const date = new Date(value);

  if (Number.isNaN(date.getTime())) {
    return value;
  }

  return new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  }).format(date);
}

function formatFullDate(value: string) {
  const date = new Date(value);

  if (Number.isNaN(date.getTime())) {
    return value;
  }

  return new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
  }).format(date);
}

export default function AgentTrendCharts({
  agent,
  history,
}: Props) {
  const chartData = [...history]
    .sort(
      (a, b) =>
        new Date(a.imported_at).getTime() -
        new Date(b.imported_at).getTime()
    )
    .map((snapshot) => ({
      ...snapshot,
      date: formatDate(snapshot.imported_at),
    }));

  if (chartData.length < 2) {
    return (
      <div className="rounded-2xl border border-white/10 bg-white/5 p-6">
        <h2 className="text-xl font-bold">
          Agent Performance Trends
        </h2>

        <p className="mt-2 text-sm text-gray-400">
          At least two imports containing this agent are needed before trend
          charts can be shown.
        </p>
      </div>
    );
  }

  const tooltipStyle = {
    backgroundColor: "#090909",
    border: "1px solid rgba(255,255,255,.12)",
    borderRadius: "12px",
    color: "#ffffff",
  };

  return (
    <div>
      <div>
        <h2 className="text-xl font-bold">
          Agent Performance Trends
        </h2>

        <p className="mt-1 text-sm text-gray-400">
          Historical team performance for {agent}.
        </p>
      </div>

      <div className="mt-4 grid gap-4 xl:grid-cols-2">
        {/* DIAMONDS */}

        <div className="rounded-2xl border border-white/10 bg-white/5 p-5">
          <p className="text-sm text-gray-400">
            Team Diamonds
          </p>

          <p className="mt-1 text-xs text-gray-600">
            Total diamonds generated by the agent&apos;s creators
          </p>

          <div className="mt-5 h-[300px]">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart
                data={chartData}
                margin={{
                  top: 10,
                  right: 15,
                  left: 10,
                  bottom: 5,
                }}
              >
                <CartesianGrid
                  strokeDasharray="3 3"
                  stroke="rgba(255,255,255,.08)"
                />

                <XAxis
                  dataKey="date"
                  stroke="#737373"
                  tick={{
                    fill: "#a3a3a3",
                    fontSize: 12,
                  }}
                />

                <YAxis
                  stroke="#737373"
                  tick={{
                    fill: "#a3a3a3",
                    fontSize: 12,
                  }}
                  tickFormatter={(value) =>
                    Number(value).toLocaleString()
                  }
                />

                <Tooltip
                  contentStyle={tooltipStyle}
                  labelFormatter={(_, payload) => {
                    const item =
                      payload?.[0]?.payload;

                    return item
                      ? formatFullDate(
                          item.imported_at
                        )
                      : "";
                  }}
                  formatter={(value) => [
                    Number(
                      value ?? 0
                    ).toLocaleString(),
                    "Diamonds",
                  ]}
                />

                <Line
                  type="monotone"
                  dataKey="diamonds"
                  stroke="#ef4444"
                  strokeWidth={3}
                  dot={{
                    r: 4,
                    fill: "#ef4444",
                  }}
                  activeDot={{
                    r: 6,
                  }}
                />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* COMPLETION */}

        <div className="rounded-2xl border border-white/10 bg-white/5 p-5">
          <p className="text-sm text-gray-400">
            Completion Rate
          </p>

          <p className="mt-1 text-xs text-gray-600">
            Percentage of creators meeting both requirements
          </p>

          <div className="mt-5 h-[300px]">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart
                data={chartData}
                margin={{
                  top: 10,
                  right: 15,
                  left: 10,
                  bottom: 5,
                }}
              >
                <CartesianGrid
                  strokeDasharray="3 3"
                  stroke="rgba(255,255,255,.08)"
                />

                <XAxis
                  dataKey="date"
                  stroke="#737373"
                  tick={{
                    fill: "#a3a3a3",
                    fontSize: 12,
                  }}
                />

                <YAxis
                  domain={[0, 100]}
                  stroke="#737373"
                  tick={{
                    fill: "#a3a3a3",
                    fontSize: 12,
                  }}
                  tickFormatter={(value) =>
                    `${Number(value).toFixed(0)}%`
                  }
                />

                <Tooltip
                  contentStyle={tooltipStyle}
                  labelFormatter={(_, payload) => {
                    const item =
                      payload?.[0]?.payload;

                    return item
                      ? formatFullDate(
                          item.imported_at
                        )
                      : "";
                  }}
                  formatter={(value) => [
                    `${Number(value ?? 0).toFixed(1)}%`,
                    "Completion",
                  ]}
                />

                <Line
                  type="monotone"
                  dataKey="completionRate"
                  stroke="#22c55e"
                  strokeWidth={3}
                  dot={{
                    r: 4,
                    fill: "#22c55e",
                  }}
                  activeDot={{
                    r: 6,
                  }}
                />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* MATCHES */}

        <div className="rounded-2xl border border-white/10 bg-white/5 p-5">
          <p className="text-sm text-gray-400">
            Team Matches
          </p>

          <p className="mt-1 text-xs text-gray-600">
            Match activity across the agent&apos;s roster
          </p>

          <div className="mt-5 h-[300px]">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart
                data={chartData}
                margin={{
                  top: 10,
                  right: 15,
                  left: 10,
                  bottom: 5,
                }}
              >
                <CartesianGrid
                  strokeDasharray="3 3"
                  stroke="rgba(255,255,255,.08)"
                />

                <XAxis
                  dataKey="date"
                  stroke="#737373"
                  tick={{
                    fill: "#a3a3a3",
                    fontSize: 12,
                  }}
                />

                <YAxis
                  stroke="#737373"
                  tick={{
                    fill: "#a3a3a3",
                    fontSize: 12,
                  }}
                />

                <Tooltip
                  contentStyle={tooltipStyle}
                  labelFormatter={(_, payload) => {
                    const item =
                      payload?.[0]?.payload;

                    return item
                      ? formatFullDate(
                          item.imported_at
                        )
                      : "";
                  }}
                  formatter={(value) => [
                    Number(
                      value ?? 0
                    ).toLocaleString(),
                    "Matches",
                  ]}
                />

                <Line
                  type="monotone"
                  dataKey="matches"
                  stroke="#a855f7"
                  strokeWidth={3}
                  dot={{
                    r: 4,
                    fill: "#a855f7",
                  }}
                  activeDot={{
                    r: 6,
                  }}
                />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* NEED ATTENTION */}

        <div className="rounded-2xl border border-white/10 bg-white/5 p-5">
          <p className="text-sm text-gray-400">
            Needs Attention
          </p>

          <p className="mt-1 text-xs text-gray-600">
            Creators who are not yet meeting both requirements
          </p>

          <div className="mt-5 h-[300px]">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart
                data={chartData}
                margin={{
                  top: 10,
                  right: 15,
                  left: 10,
                  bottom: 5,
                }}
              >
                <CartesianGrid
                  strokeDasharray="3 3"
                  stroke="rgba(255,255,255,.08)"
                />

                <XAxis
                  dataKey="date"
                  stroke="#737373"
                  tick={{
                    fill: "#a3a3a3",
                    fontSize: 12,
                  }}
                />

                <YAxis
                  stroke="#737373"
                  tick={{
                    fill: "#a3a3a3",
                    fontSize: 12,
                  }}
                />

                <Tooltip
                  contentStyle={tooltipStyle}
                  labelFormatter={(_, payload) => {
                    const item =
                      payload?.[0]?.payload;

                    return item
                      ? formatFullDate(
                          item.imported_at
                        )
                      : "";
                  }}
                  formatter={(value) => [
                    Number(
                      value ?? 0
                    ).toLocaleString(),
                    "Need Attention",
                  ]}
                />

                <Line
                  type="monotone"
                  dataKey="needsAttention"
                  stroke="#f59e0b"
                  strokeWidth={3}
                  dot={{
                    r: 4,
                    fill: "#f59e0b",
                  }}
                  activeDot={{
                    r: 6,
                  }}
                />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>
    </div>
  );
}